name: Keepalive

on:
  schedule:
    - cron: '0 3 1 * *'

permissions:
  contents: write

jobs:
  touch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Touch
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          touch .keepalive
          git add .keepalive
          git diff --staged --quiet || git commit -m "keepalive"
          git push
